### ISSUE TITLE
underflow output 

### ISSUE THREAD

**Issue by tkkhuu** [mooshim/Mooshimeter-PythonAPI#3]
Hi,

I'm running the Example.py code and it seems that I'm able to connect to my Mooshimeter. But I'm getting underflow output and 2 channels instead of what was described here: https://moosh.im/2015/03/talk-to-your-mooshimeter-from-python/

I tried to measure resistance but didn't see any changes, is there some command I have to type to switch to resistance measurement?

This is the output on my screen:
![mooshi_example_output](https://user-images.githubusercontent.com/11468106/32555548-10f97940-c46b-11e7-85e8-6787cb463b9f.PNG)

**Comment by jwhong** [comment]
Thanks for bringing this up - that's a deprecated debug message I left in there.  Removed.

**Comment by jwhong** [comment]
Oh - regarding your second question, how to set to resistance measurement: you need to change the mapping of the sampling channels to resistance.  Change the lines:

        m.sendCommand('ch2:mapping 0')         # CH2 select voltage input
        m.sendCommand('ch2:range_i 1')         # CH2 Voltage 600V range

To


m.sendCommand('ch2:mapping 2')  # CH2 select shared input
m.sendCommand('shared 1')            # Map shared channel to resistance
m.sendCommand('ch2:range_i 2')    # CH2 Resistance 100k range

**Comment by tkkhuu** [comment]
Oh okay I got it, thank you so much James
